# Generated by Django 4.0.1 on 2022-01-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finch',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='finch',
            name='family',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='finch',
            name='fav_food',
            field=models.CharField(max_length=150),
        ),
    ]
